name: Ruby

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} & Rails ${{ matrix.rails_version }}
    strategy:
      matrix:
        ruby:
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
        rails_version:
          - '6.0'
          - '6.1'
          - '7.0'
        exclude:
          - ruby: '2.6'
            rails_version: '7.0'

    env:
      RAILS_VERSION: "~> ${{ matrix.rails_version }}.0"
      UPLOAD_COVERAGE_TO_CODECLIMATE: true

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Setup Code Climate test-reporter
      if: matrix.ruby == '3.1' && matrix.rails_version == '7.0'
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Run the default task
      run: bundle exec rake

    - name: Publish code coverage
      if: matrix.ruby == '3.1' && matrix.rails_version == '7.0'
      run: |
        export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
        ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}